import { useLoggedInUser } from "@/hooks/useLoggedInUser";
import { useProject } from "@/hooks/useProject";
import { useAppSelector } from "@/store/hooks";
import styles from "@/styles/main.module.scss";
import { Project, ProjectLoading } from "@/views/Project";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useLoggedInUser();
  useProject();

  const project = useAppSelector((state) => state.projects.project);

  return (
    <>
      <Head>
        <title>Task Management - Projects - </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {project ? <Project /> : <ProjectLoading />}
      </main>
    </>
  );
}
