import { useLoggedInUser } from "@/hooks/useLoggedInUser";
import styles from "@/styles/main.module.scss";
import { Projects } from "@/views/Projects";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useLoggedInUser();

  return (
    <>
      <Head>
        <title>Task Management - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Projects />
      </main>
    </>
  );
}
